/****************************************************************
 ---------------------------------------------------------------
     Copyright 1999 Sun Microsystems, Inc., 901 San Antonio
     Road, Palo Alto, CA 94303, U.S.A.  All Rights Reserved.
     The contents of this file are subject to the current
     version of the Sun Community Source License, picoJava-II
     Core ("the License").  You may not use this file except
     in compliance with the License.  You may obtain a copy
     of the License by searching for "Sun Community Source
     License" on the World Wide Web at http://www.sun.com.
     See the License for the rights, obligations, and
     limitations governing use of the contents of this file.

     Sun, Sun Microsystems, the Sun logo, and all Sun-based
     trademarks and logos, Java, picoJava, and all Java-based
     trademarks and logos are trademarks or registered trademarks 
     of Sun Microsystems, Inc. in the United States and other
     countries.
 ----------------------------------------------------------------
******************************************************************/




 // instruction mnemonics and their opcodes

`define INST_nop 			8'h00
`define INST_aconst_null 		8'h01
`define INST_iconst_m1 			8'h02
`define INST_iconst_0 			8'h03
`define INST_iconst_1 			8'h04
`define INST_iconst_2 			8'h05
`define INST_iconst_3 			8'h06
`define INST_iconst_4 			8'h07
`define INST_iconst_5 			8'h08
`define INST_lconst_0 			8'h09
`define INST_lconst_1 			8'h0a
`define INST_fconst_0 			8'h0b
`define INST_fconst_1 			8'h0c
`define INST_fconst_2 			8'h0d
`define INST_dconst_0 			8'h0e
`define INST_dconst_1 			8'h0f
`define INST_bipush 			8'h10
`define INST_sipush 			8'h11
`define INST_ldc 			8'h12
`define INST_ldc_w 			8'h13
`define INST_ldc2_w 			8'h14
`define INST_iload 			8'h15
`define INST_lload 			8'h16
`define INST_fload 			8'h17
`define INST_dload 			8'h18
`define INST_aload 			8'h19
`define INST_iload_0			8'h1a
`define INST_iload_1			8'h1b
`define INST_iload_2			8'h1c
`define INST_iload_3			8'h1d
`define INST_lload_0			8'h1e
`define INST_lload_1			8'h1f
`define INST_lload_2			8'h20
`define INST_lload_3			8'h21
`define INST_fload_0			8'h22
`define INST_fload_1			8'h23
`define INST_fload_2			8'h24
`define INST_fload_3			8'h25
`define INST_dload_0			8'h26
`define INST_dload_1			8'h27
`define INST_dload_2			8'h28
`define INST_dload_3			8'h29
`define INST_aload_0			8'h2a
`define INST_aload_1			8'h2b
`define INST_aload_2			8'h2c
`define INST_aload_3			8'h2d
`define INST_iaload 			8'h2e
`define INST_laload 			8'h2f
`define INST_faload 			8'h30
`define INST_daload 			8'h31
`define INST_aaload 			8'h32
`define INST_baload 			8'h33
`define INST_caload 			8'h34
`define INST_saload 			8'h35
`define INST_istore 			8'h36
`define INST_lstore 			8'h37
`define INST_fstore 			8'h38
`define INST_dstore 			8'h39
`define INST_astore 			8'h3a
`define INST_istore_0			8'h3b
`define INST_istore_1 			8'h3c
`define INST_istore_2 			8'h3d
`define INST_istore_3 			8'h3e
`define INST_lstore_0 			8'h3f
`define INST_lstore_1 			8'h40
`define INST_lstore_2 			8'h41
`define INST_lstore_3 			8'h42
`define INST_fstore_0 			8'h43
`define INST_fstore_1 			8'h44
`define INST_fstore_2 			8'h45
`define INST_fstore_3 			8'h46
`define INST_dstore_0 			8'h47
`define INST_dstore_1 			8'h48
`define INST_dstore_2 			8'h49
`define INST_dstore_3 			8'h4a
`define INST_astore_0 			8'h4b
`define INST_astore_1 			8'h4c
`define INST_astore_2 			8'h4d
`define INST_astore_3 			8'h4e
`define INST_iastore 			8'h4f
`define INST_lastore 			8'h50
`define INST_fastore 			8'h51
`define INST_dastore 			8'h52
`define INST_aastore 			8'h53
`define INST_bastore 			8'h54
`define INST_castore 			8'h55
`define INST_sastore 			8'h56
`define INST_pop 			8'h57
`define INST_pop2 			8'h58
`define INST_dup 			8'h59
`define INST_dup_x1 			8'h5a
`define INST_dup_x2 			8'h5b
`define INST_dup2 			8'h5c
`define INST_dup2_x1 			8'h5d
`define INST_dup2_x2 			8'h5e
`define INST_swap 			8'h5f
`define INST_iadd 			8'h60
`define INST_ladd 			8'h61
`define INST_fadd 			8'h62
`define INST_dadd 			8'h63
`define INST_isub 			8'h64
`define INST_lsub 			8'h65
`define INST_fsub 			8'h66
`define INST_dsub 			8'h67
`define INST_imul 			8'h68
`define INST_lmul 			8'h69
`define INST_fmul 			8'h6a
`define INST_dmul 			8'h6b
`define INST_idiv 			8'h6c
`define INST_ldiv 			8'h6d
`define INST_fdiv 			8'h6e
`define INST_ddiv 			8'h6f
`define INST_irem 			8'h70
`define INST_lrem 			8'h71
`define INST_frem 			8'h72
`define INST_drem 			8'h73
`define INST_ineg 			8'h74
`define INST_lneg 			8'h75
`define INST_fneg 			8'h76
`define INST_dneg 			8'h77
`define INST_ishl 			8'h78
`define INST_lshl 			8'h79
`define INST_ishr 			8'h7a
`define INST_lshr 			8'h7b
`define INST_iushr 			8'h7c
`define INST_lushr 			8'h7d
`define INST_iand 			8'h7e
`define INST_land 			8'h7f
`define INST_ior 			8'h80
`define INST_lor 			8'h81
`define INST_ixor 			8'h82
`define INST_lxor 			8'h83
`define INST_iinc 			8'h84
`define INST_i2l 			8'h85
`define INST_i2f 			8'h86
`define INST_i2d 			8'h87
`define INST_l2i 			8'h88
`define INST_l2f 			8'h89
`define INST_l2d 			8'h8a
`define INST_f2i 			8'h8b
`define INST_f2l 			8'h8c
`define INST_f2d 			8'h8d
`define INST_d2i 			8'h8e
`define INST_d2l 			8'h8f
`define INST_d2f 			8'h90
`define INST_i2b 			8'h91
`define INST_i2c 			8'h92
`define INST_i2s 			8'h93
`define INST_lcmp 			8'h94
`define INST_fcmpl 			8'h95
`define INST_fcmpg 			8'h96
`define INST_dcmpl 			8'h97
`define INST_dcmpg 			8'h98
`define INST_ifeq 			8'h99
`define INST_ifne 			8'h9a
`define INST_iflt 			8'h9b
`define INST_ifge 			8'h9c
`define INST_ifgt 			8'h9d
`define INST_ifle 			8'h9e
`define INST_if_icmpeq 			8'h9f
`define INST_if_icmpne 			8'ha0
`define INST_if_icmplt 			8'ha1
`define INST_if_icmpge 			8'ha2
`define INST_if_icmpgt 			8'ha3
`define INST_if_icmple 			8'ha4
`define INST_if_acmpeq 			8'ha5
`define INST_if_acmpne 			8'ha6
`define INST_goto 			8'ha7
`define INST_jsr 			8'ha8
`define INST_ret 			8'ha9
`define INST_tableswitch 		8'haa
`define INST_lookupswitch 		8'hab
`define INST_ireturn 			8'hac
`define INST_lreturn 			8'had
`define INST_freturn 			8'hae
`define INST_dreturn 			8'haf
`define INST_areturn 			8'hb0
`define INST_return 			8'hb1
`define INST_getstatic 			8'hb2
`define INST_putstatic 			8'hb3
`define INST_getfield 			8'hb4
`define INST_putfield 			8'hb5
`define INST_invokevirtual 		8'hb6
`define INST_invokespecial 		8'hb7
`define INST_invokestatic 		8'hb8
`define INST_invokeinterface		8'hb9
`define INST_opcode_0xba		8'hba
`define INST_new 			8'hbb
`define INST_newarray 			8'hbc
`define INST_anewarray 			8'hbd
`define INST_arraylength 		8'hbe
`define INST_athrow 			8'hbf
`define INST_checkcast 			8'hc0
`define INST_instanceof 		8'hc1
`define INST_monitorenter 		8'hc2
`define INST_monitorexit 		8'hc3
`define INST_wide			8'hc4
`define INST_multianewarray 		8'hc5
`define INST_ifnull 			8'hc6
`define INST_ifnonnull 			8'hc7
`define INST_goto_w 			8'hc8
`define INST_jsr_w 			8'hc9
`define INST_breakpoint 		8'hca
`define INST_ldc_quick			8'hcb
`define INST_ldc_w_quick		8'hcc
`define INST_ldc2_w_quick		8'hcd
`define INST_getfield_quick		8'hce
`define INST_putfield_quick		8'hcf
`define INST_getfield2_quick		8'hd0
`define INST_putfield2_quick		8'hd1
`define INST_getstatic_quick		8'hd2
`define INST_putstatic_quick		8'hd3
`define INST_getstatic2_quick		8'hd4
`define INST_putstatic2_quick		8'hd5
`define INST_invokevirtual_quick	8'hd6
`define INST_invokenonvirtual_quick	8'hd7
`define INST_invokesuper_quick		8'hd8
`define INST_invokestatic_quick		8'hd9
`define INST_invokeinterface_quick	8'hda
`define INST_invokevirtualobj_quick	8'hdb
`define INST_opcode_0xdc 		8'hdc
`define INST_new_quick			8'hdd
`define INST_anewarray_quick		8'hde
`define INST_multianewarray_quick	8'hdf
`define INST_checkcast_quick		8'he0
`define INST_instanceof_quick		8'he1
`define INST_invokevirtual_quick_w	8'he2
`define INST_getfield_quick_w		8'he3
`define INST_putfield_quick_w		8'he4
`define INST_nonnull_quick 		8'he5
`define INST_agetfield_quick		8'he6
`define INST_aputfield_quick		8'he7
`define INST_agetstatic_quick		8'he8
`define INST_aputstatic_quick		8'he9
`define INST_aldc_quick			8'hea
`define INST_aldc_w_quick		8'heb
`define INST_exit_sync_method 		8'hec
`define INST_sethi 			8'hed
`define INST_opcode_0xee 		8'hee
`define INST_opcode_0xef 		8'hef
`define INST_opcode_0xf0 		8'hf0
`define INST_opcode_0xf1 		8'hf1
`define INST_opcode_0xf2 		8'hf2
`define INST_opcode_0xf3 		8'hf3
`define INST_opcode_0xf4 		8'hf4
`define INST_opcode_0xf5 		8'hf5
`define INST_opcode_0xf6 		8'hf6
`define INST_opcode_0xf7 		8'hf7
`define INST_opcode_0xf8 		8'hf8
`define INST_opcode_0xf9 		8'hf9
`define INST_opcode_0xfa 		8'hfa
`define INST_opcode_0xfb 		8'hfb
`define INST_opcode_0xfc 		8'hfc
`define INST_opcode_0xfe 		8'hfe

`define INST_load_ubyte 		8'h00
`define INST_load_byte 			8'h01
`define INST_load_char 			8'h02
`define INST_load_short 		8'h03
`define INST_load_word 			8'h04
`define INST_priv_ret_from_trap 	8'h05
`define INST_priv_read_dcache_tag 	8'h06
`define INST_priv_read_dcache_data 	8'h07
`define INST_opcode_0xff08 		8'h08
`define INST_opcode_0xff09 		8'h09
`define INST_load_char_oe 		8'h0a
`define INST_load_short_oe 		8'h0b
`define INST_load_word_oe 		8'h0c
`define INST_return0 			8'h0d
`define INST_priv_read_icache_tag 	8'h0e
`define INST_priv_read_icache_data 	8'h0f
`define INST_ncload_ubyte 		8'h10
`define INST_ncload_byte 		8'h11
`define INST_ncload_char 		8'h12
`define INST_ncload_short 		8'h13
`define INST_ncload_word 		8'h14
`define INST_iu_cmp			8'h15
`define INST_priv_powerdown 		8'h16
`define INST_cache_invalidate 		8'h17
`define INST_opcode_0xff18 		8'h18
`define INST_opcode_0xff19 		8'h19
`define INST_ncload_char_oe 		8'h1a
`define INST_ncload_short_oe 		8'h1b
`define INST_ncload_word_oe 		8'h1c
`define INST_return1 			8'h1d
`define INST_cache_flush 		8'h1e
`define INST_cache_index_flush 		8'h1f
`define INST_store_byte 		8'h20
`define INST_opcode_0xff21 		8'h21
`define INST_store_short 		8'h22
`define INST_opcode_0xff23 		8'h23
`define INST_store_word 		8'h24
`define INST_soft_trap 			8'h25
`define INST_priv_write_dcache_tag 	8'h26
`define INST_priv_write_dcache_data 	8'h27
`define INST_opcode_0xff28 		8'h28
`define INST_opcode_0xff29 		8'h29
`define INST_store_short_oe 		8'h2a
`define INST_opcode_0xff2b 		8'h2b
`define INST_store_word_oe 		8'h2c
`define INST_return2 			8'h2d
`define INST_priv_write_icache_tag 	8'h2e
`define INST_priv_write_icache_data	8'h2f
`define INST_ncstore_byte 		8'h30
`define INST_opcode_0xff31 		8'h31
`define INST_ncstore_short 		8'h32
`define INST_opcode_0xff33 		8'h33
`define INST_ncstore_word 		8'h34
`define INST_opcode_0xff35		8'h35
`define INST_priv_reset 		8'h36
`define INST_get_current_class 		8'h37
`define INST_opcode_0xff38 		8'h38
`define INST_opcode_0xff39 		8'h39
`define INST_ncstore_short_oe 		8'h3a
`define INST_opcode_0xff3b 		8'h3b
`define INST_ncstore_word_oe 		8'h3c
`define INST_call 			8'h3d
`define INST_zero_line 			8'h3e
`define INST_priv_update_optop 		8'h3f
`define INST_read_pc 			8'h40
`define INST_read_vars 			8'h41
`define INST_read_frame 		8'h42
`define INST_read_optop 		8'h43
`define INST_priv_read_oplim 		8'h44
`define INST_read_const_pool 		8'h45
`define INST_priv_read_psr 		8'h46
`define INST_priv_read_trapbase 	8'h47
`define INST_priv_read_lockcount0 	8'h48
`define INST_priv_read_lockcount1 	8'h49
`define INST_opcode_0xff4a 		8'h4a
`define INST_opcode_0xff4b 		8'h4b
`define INST_priv_read_lockaddr0 	8'h4c
`define INST_priv_read_lockaddr1 	8'h4d
`define INST_opcode_0xff4e 		8'h4e
`define INST_opcode_0xff4f 		8'h4f
`define INST_priv_read_userrange1 	8'h50
`define INST_priv_read_gc_config 	8'h51
`define INST_priv_read_brk1a 		8'h52
`define INST_priv_read_brk2a 		8'h53
`define INST_priv_read_brk12c 		8'h54
`define INST_priv_read_userrange2 	8'h55
`define INST_opcode_0xff56 		8'h56
`define INST_priv_read_versionid 	8'h57
`define INST_priv_read_hcr 		8'h58
`define INST_priv_read_sc_bottom 	8'h59
`define INST_read_global0 		8'h5a
`define INST_read_global1 		8'h5b
`define INST_read_global2 		8'h5c
`define INST_read_global3 		8'h5d
`define INST_opcode_0xff5e 		8'h5e
`define INST_opcode_0xff5f 		8'h5f
`define INST_ret_from_sub 		8'h60
`define INST_write_vars 		8'h61
`define INST_write_frame 		8'h62
`define INST_write_optop 		8'h63
`define INST_priv_write_oplim 		8'h64
`define INST_write_const_pool 		8'h65
`define INST_priv_write_psr 		8'h66
`define INST_priv_write_trapbase 	8'h67
`define INST_priv_write_lockcount0 	8'h68
`define INST_priv_write_lockcount1 	8'h69
`define INST_opcode_0xff6a 		8'h6a
`define INST_opcode_0xff6b 		8'h6b
`define INST_priv_write_lockaddr0 	8'h6c
`define INST_priv_write_lockaddr1 	8'h6d
`define INST_opcode_0xff6e 		8'h6e
`define INST_opcode_0xff6f 		8'h6f
`define INST_priv_write_userrange1 	8'h70
`define INST_priv_write_gc_config 	8'h71
`define INST_priv_write_brk1a 		8'h72
`define INST_priv_write_brk2a 		8'h73
`define INST_priv_write_brk12c 		8'h74
`define INST_priv_write_userrange2 	8'h75
`define INST_opcode_0xff76 		8'h76
`define INST_opcode_0xff77 		8'h77
`define INST_opcode_0xff78 		8'h78
`define INST_priv_write_sc_bottom 	8'h79
`define INST_write_global0 		8'h7a
`define INST_write_global1 		8'h7b
`define INST_write_global2 		8'h7c
`define INST_write_global3 		8'h7d
`define INST_opcode_0xff7e 		8'h7e
`define INST_opcode_0xff7f 		8'h7f
`define INST_opcode_0xff80		8'h80
`define INST_opcode_0xff81		8'h81
`define INST_opcode_0xff82		8'h82
`define INST_opcode_0xff83		8'h83
`define INST_opcode_0xff84		8'h84
`define INST_opcode_0xff85		8'h85
`define INST_opcode_0xff86		8'h86
`define INST_opcode_0xff87		8'h87
`define INST_opcode_0xff88		8'h88
`define INST_opcode_0xff89		8'h89
`define INST_opcode_0xff8a		8'h8a
`define INST_opcode_0xff8b		8'h8b
`define INST_opcode_0xff8c		8'h8c
`define INST_opcode_0xff8d		8'h8d
`define INST_opcode_0xff8e		8'h8e
`define INST_opcode_0xff8f		8'h8f
`define INST_opcode_0xff90		8'h90
`define INST_opcode_0xff91		8'h91
`define INST_opcode_0xff92		8'h92
`define INST_opcode_0xff93		8'h93
`define INST_opcode_0xff94		8'h94
`define INST_opcode_0xff95		8'h95
`define INST_opcode_0xff96		8'h96
`define INST_opcode_0xff97		8'h97
`define INST_opcode_0xff98		8'h98
`define INST_opcode_0xff99		8'h99
`define INST_opcode_0xff9a		8'h9a
`define INST_opcode_0xff9b		8'h9b
`define INST_opcode_0xff9c		8'h9c
`define INST_opcode_0xff9d		8'h9d
`define INST_opcode_0xff9e		8'h9e
`define INST_opcode_0xff9f		8'h9f
`define INST_opcode_0xffa0		8'ha0
`define INST_opcode_0xffa1		8'ha1
`define INST_opcode_0xffa2		8'ha2
`define INST_opcode_0xffa3		8'ha3
`define INST_opcode_0xffa4		8'ha4
`define INST_opcode_0xffa5		8'ha5
`define INST_opcode_0xffa6		8'ha6
`define INST_opcode_0xffa7		8'ha7
`define INST_opcode_0xffa8		8'ha8
`define INST_opcode_0xffa9		8'ha9
`define INST_opcode_0xffaa		8'haa
`define INST_opcode_0xffab		8'hab
`define INST_opcode_0xffac		8'hac
`define INST_opcode_0xffad		8'had
`define INST_opcode_0xffae		8'hae
`define INST_opcode_0xffaf		8'haf
`define INST_opcode_0xffb0		8'hb0
`define INST_opcode_0xffb1		8'hb1
`define INST_opcode_0xffb2		8'hb2
`define INST_opcode_0xffb3		8'hb3
`define INST_opcode_0xffb4		8'hb4
`define INST_opcode_0xffb5		8'hb5
`define INST_opcode_0xffb6		8'hb6
`define INST_opcode_0xffb7		8'hb7
`define INST_opcode_0xffb8		8'hb8
`define INST_opcode_0xffb9		8'hb9
`define INST_opcode_0xffba		8'hba
`define INST_opcode_0xffbb		8'hbb
`define INST_opcode_0xffbc		8'hbc
`define INST_opcode_0xffbd		8'hbd
`define INST_opcode_0xffbe		8'hbe
`define INST_opcode_0xffbf		8'hbf
`define INST_opcode_0xffc0		8'hc0
`define INST_opcode_0xffc1		8'hc1
`define INST_opcode_0xffc2		8'hc2
`define INST_opcode_0xffc3		8'hc3
`define INST_opcode_0xffc4		8'hc4
`define INST_opcode_0xffc5		8'hc5
`define INST_opcode_0xffc6		8'hc6
`define INST_opcode_0xffc7		8'hc7
`define INST_opcode_0xffc8		8'hc8
`define INST_opcode_0xffc9		8'hc9
`define INST_opcode_0xffca		8'hca
`define INST_opcode_0xffcb		8'hcb
`define INST_opcode_0xffcc		8'hcc
`define INST_opcode_0xffcd		8'hcd
`define INST_opcode_0xffce		8'hce
`define INST_opcode_0xffcf		8'hcf
`define INST_opcode_0xffd0		8'hd0
`define INST_opcode_0xffd1		8'hd1
`define INST_opcode_0xffd2		8'hd2
`define INST_opcode_0xffd3		8'hd3
`define INST_opcode_0xffd4		8'hd4
`define INST_opcode_0xffd5		8'hd5
`define INST_opcode_0xffd6		8'hd6
`define INST_opcode_0xffd7		8'hd7
`define INST_opcode_0xffd8		8'hd8
`define INST_opcode_0xffd9		8'hd9
`define INST_opcode_0xffda		8'hda
`define INST_opcode_0xffdb		8'hdb
`define INST_opcode_0xffdc		8'hdc
`define INST_opcode_0xffdd		8'hdd
`define INST_opcode_0xffde		8'hde
`define INST_opcode_0xffdf		8'hdf
`define INST_opcode_0xffe0		8'he0
`define INST_opcode_0xffe1		8'he1
`define INST_opcode_0xffe2		8'he2
`define INST_opcode_0xffe3		8'he3
`define INST_opcode_0xffe4		8'he4
`define INST_opcode_0xffe5		8'he5
`define INST_opcode_0xffe6		8'he6
`define INST_opcode_0xffe7		8'he7
`define INST_opcode_0xffe8		8'he8
`define INST_opcode_0xffe9		8'he9
`define INST_opcode_0xffea		8'hea
`define INST_opcode_0xffeb		8'heb
`define INST_opcode_0xffec		8'hec
`define INST_opcode_0xffed		8'hed
`define INST_opcode_0xffee		8'hee
`define INST_opcode_0xffef		8'hef
`define INST_opcode_0xfff0		8'hf0
`define INST_opcode_0xfff1		8'hf1
`define INST_opcode_0xfff2		8'hf2
`define INST_opcode_0xfff3		8'hf3
`define INST_opcode_0xfff4		8'hf4
`define INST_opcode_0xfff5		8'hf5
`define INST_opcode_0xfff6		8'hf6
`define INST_opcode_0xfff7		8'hf7
`define INST_opcode_0xfff8		8'hf8
`define INST_opcode_0xfff9		8'hf9
`define INST_opcode_0xfffa		8'hfa
`define INST_opcode_0xfffb		8'hfb
`define INST_opcode_0xfffc		8'hfc
`define INST_opcode_0xfffd		8'hfd
`define INST_opcode_0xfffe		8'hfe
`define INST_opcode_0xffff		8'hff
